"""Add items table.

Revision ID: 0c5a24ddc71b
Revises: b65791a62e04
Create Date: 2020-12-05 19:15:36.144483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5a24ddc71b'
down_revision = 'b65791a62e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonuses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hp', sa.Integer(), nullable=False),
                    sa.Column('strn', sa.Integer(), nullable=False),
                    sa.Column('vit', sa.Integer(), nullable=False),
                    sa.Column('dex', sa.Integer(), nullable=False),
                    sa.Column('acc', sa.Integer(), nullable=False),
                    sa.Column('dmg', sa.Integer(), nullable=False),
                    sa.Column('crit_chance', sa.Integer(), nullable=False),
                    sa.Column('crit_power', sa.Integer(), nullable=False),
                    sa.Column('time', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('item_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('slug')
                    )

    op.create_table('set_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('slug')
                    )

    op.create_table('items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.Column('item_type_id', sa.Integer(), nullable=False),
                    sa.Column('set_type_id', sa.Integer(), nullable=False),
                    sa.Column('bonus_id', sa.Integer(), nullable=False),
                    sa.Column('bonus_2items_id', sa.Integer(), nullable=False),
                    sa.Column('bonus_fullset_id',
                              sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['bonus_2items_id'], ['bonuses.id'],),
                    sa.ForeignKeyConstraint(
                        ['bonus_fullset_id'], ['bonuses.id'],),
                    sa.ForeignKeyConstraint(['bonus_id'], ['bonuses.id'],),
                    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'],
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['set_type_id'], ['set_types.id'],
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('slug'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('set_types')
    op.drop_table('item_types')
    op.drop_table('bonuses')
    # ### end Alembic commands ###
