"""Add item_templates table.

Revision ID: 1d3966b0946a
Revises: c45a6157275a
Create Date: 2020-12-06 20:52:55.517575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3966b0946a'
down_revision = 'c45a6157275a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_templates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.Column('item_type_id', sa.Integer(), nullable=False),
                    sa.Column('set_type_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['item_type_id'], [
                        'item_types.id'], name='item_templates_item_type_id', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['set_type_id'], [
                        'set_types.id'], name='item_templates_set_type_id', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('slug')
                    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_template_id',
                                      sa.Integer(), nullable=False))
        batch_op.drop_constraint('items_set_type_id', type_='foreignkey')
        batch_op.drop_constraint('items_item_type_id', type_='foreignkey')
        batch_op.create_foreign_key('items_item_item_template_id', 'item_templates', [
                                    'item_template_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('item_type_id')
        batch_op.drop_column('set_type_id')
        batch_op.drop_column('name')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('slug', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(
            sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(
            sa.Column('set_type_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(
            sa.Column('item_type_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(
            'items_item_item_template_id', type_='foreignkey')
        batch_op.create_foreign_key('items_item_type_id', 'item_types', [
                                    'item_type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('items_set_type_id', 'set_types', [
                                    'set_type_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('item_template_id')

    op.drop_table('item_templates')
    # ### end Alembic commands ###
