"""Add bonus_id field into item_templates table.

Revision ID: 0612b1984ec8
Revises: 8fa0a21e761b
Create Date: 2020-12-27 17:48:13.935080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0612b1984ec8'
down_revision = '8fa0a21e761b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_templates', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('bonus_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('item_templates_bonus_id', 'bonuses',
                                    ['bonus_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_templates', schema=None) as batch_op:
        batch_op.drop_constraint('item_templates_bonus_id', type_='foreignkey')
        batch_op.drop_column('bonus_id')

    # ### end Alembic commands ###
