"""Add stats table.

Revision ID: e631352c5582
Revises: f68df277edf0
Create Date: 2020-11-29 18:08:38.242924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e631352c5582'
down_revision = 'f68df277edf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lvl', sa.Integer(), nullable=False),
                    sa.Column('hp', sa.Integer(), nullable=False),
                    sa.Column('exp', sa.Integer(), nullable=False),
                    sa.Column('strn', sa.Integer(), nullable=False),
                    sa.Column('vit', sa.Integer(), nullable=False),
                    sa.Column('dex', sa.Integer(), nullable=False),
                    sa.Column('acc', sa.Integer(), nullable=False),
                    sa.Column('dmg', sa.Integer(), nullable=False),
                    sa.Column('stats', sa.Integer(), nullable=False),
                    sa.Column('bosses_defeated', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
